{{- if not .Values.zensu.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zensu-monitoring-agent.fullname" . }}
  labels:
    {{- include "zensu-monitoring-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZENSU_API_KEY: {{ required "Set zensu.apiKey or zensu.existingSecret" .Values.zensu.apiKey | quote }}
{{- end }}
