{{- if and (eq .Values.agent.mode "deployment") .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zensu-monitoring-agent.fullname" . }}-metrics
  labels:
    {{- include "zensu-monitoring-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "zensu-monitoring-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
